openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /api/v1/collections/:
    post:
      operationId: v1_collections_create
      tags:
      - Collections
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Collection'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Collection'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Collection'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collection'
          description: ''
        '400':
          description: Validation Error
  /api/v1/collections/{collection_id}:
    patch:
      operationId: v1_collections_partial_update
      parameters:
      - in: path
        name: collection_id
        schema:
          type: integer
        required: true
      tags:
      - Collections
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCollection'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCollection'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCollection'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collection'
          description: ''
        '400':
          description: Validation Error
        '403':
          description: Forbidden
        '404':
          description: Collection not found
    delete:
      operationId: v1_collections_destroy
      parameters:
      - in: path
        name: collection_id
        schema:
          type: integer
        required: true
      tags:
      - Collections
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
        '403':
          description: Forbidden
        '404':
          description: Collection not found
  /api/v1/reviews/:
    post:
      operationId: v1_reviews_create
      tags:
      - Reviews
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Review'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
        '400':
          description: Validation Error
  /api/v1/reviews/{review_id}/:
    patch:
      operationId: v1_reviews_partial_update
      parameters:
      - in: path
        name: review_id
        schema:
          type: integer
        required: true
      tags:
      - Reviews
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedReview'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedReview'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedReview'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
        '400':
          description: Validation Error
        '403':
          description: Forbidden
        '404':
          description: Review not found
    delete:
      operationId: v1_reviews_destroy
      parameters:
      - in: path
        name: review_id
        schema:
          type: integer
        required: true
      tags:
      - Reviews
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
        '403':
          description: Forbidden
        '404':
          description: Review not found
  /api/v1/reviews/search/:
    get:
      operationId: v1_reviews_search_list
      parameters:
      - in: query
        name: query
        schema:
          type: string
        required: true
      - in: query
        name: user_id
        schema:
          type: integer
        required: true
      tags:
      - Reviews
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReviewSearch'
          description: ''
  /api/v1/tags/get/:
    get:
      operationId: v1_tags_get_list
      parameters:
      - in: query
        name: query
        schema:
          type: string
        required: true
      tags:
      - ReviewTags
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReviewTag'
          description: ''
components:
  schemas:
    Collection:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 127
        description:
          type: string
        cover:
          type: string
          format: uri
        reviews:
          type: array
          items:
            type: integer
            writeOnly: true
          writeOnly: true
        review_details:
          type: array
          items:
            type: integer
          readOnly: true
        user:
          type: integer
          readOnly: true
      required:
      - cover
      - id
      - review_details
      - reviews
      - title
      - user
    PatchedCollection:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 127
        description:
          type: string
        cover:
          type: string
          format: uri
        reviews:
          type: array
          items:
            type: integer
            writeOnly: true
          writeOnly: true
        review_details:
          type: array
          items:
            type: integer
          readOnly: true
        user:
          type: integer
          readOnly: true
    PatchedReview:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 127
        description:
          type: string
        rating:
          allOf:
          - $ref: '#/components/schemas/RatingEnum'
          minimum: -32768
          maximum: 32767
        cover:
          type: string
          format: uri
        tags:
          type: array
          items:
            type: integer
        user:
          type: integer
          readOnly: true
    RatingEnum:
      enum:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      type: integer
      description: |-
        * `1` - 1
        * `2` - 2
        * `3` - 3
        * `4` - 4
        * `5` - 5
        * `6` - 6
        * `7` - 7
        * `8` - 8
        * `9` - 9
        * `10` - 10
    Review:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 127
        description:
          type: string
        rating:
          allOf:
          - $ref: '#/components/schemas/RatingEnum'
          minimum: -32768
          maximum: 32767
        cover:
          type: string
          format: uri
        tags:
          type: array
          items:
            type: integer
        user:
          type: integer
          readOnly: true
      required:
      - id
      - rating
      - title
      - user
    ReviewSearch:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 127
        rating:
          allOf:
          - $ref: '#/components/schemas/RatingEnum'
          minimum: -32768
          maximum: 32767
        cover:
          type: string
          format: uri
      required:
      - id
      - rating
      - title
    ReviewTag:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 127
      required:
      - id
      - name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
