# Generated by Django 5.1.6 on 2025-08-28 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.reviewtype'),
        ),
        migrations.AlterField(
            model_name='reviewtype',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
