# Generated by Django 5.1.6 on 2025-08-08 21:27

import django.db.models.deletion
import review_collections.models
import reviews.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, validators=[reviews.validators.validate_description_length])),
                ('cover', models.ImageField(default='collections/default.jpg', upload_to=review_collections.models.cover_upload_to_path)),
                ('reviews', models.ManyToManyField(related_name='collections', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
