# Generated by Django 5.1.6 on 2025-07-23 15:16

import item_collections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover',
            field=models.ImageField(default='collections/default.jpg', upload_to=item_collections.models.cover_upload_to_path),
        ),
    ]
