# Generated by Django 5.1.6 on 2025-07-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_collections', '0002_alter_collection_cover'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(related_name='collections', to='items.item'),
        ),
    ]
